CREATE TABLE Users
(
    Id           UNIQUEIDENTIFIER  NOT NULL DEFAULT NEWSEQUENTIALID(),
    Email        NVARCHAR(256)     NOT NULL,
    PasswordHash VARCHAR(256)      NOT NULL,
    CreatedAt    DATETIMEOFFSET    NOT NULL,
    UpdatedAt    DATETIMEOFFSET    NOT NULL,

    CONSTRAINT PK_Users PRIMARY KEY (Id)
);