CREATE TABLE Roles
(
    Id   UNIQUEIDENTIFIER  NOT NULL DEFAULT NEWSEQUENTIALID(),
    Name VARCHAR(20) NOT NULL,

    CONSTRAINT PK_Roles      PRIMARY KEY (Id),
    CONSTRAINT UQ_Roles_Name UNIQUE (Name)
);