CREATE TABLE Organizations
(
    Id        UNIQUEIDENTIFIER  NOT NULL DEFAULT NEWSEQUENTIALID(),
    Name      NVARCHAR(256)     NOT NULL,
    CreatedAt DATETIMEOFFSET    NOT NULL,
    UpdatedAt DATETIMEOFFSET    NOT NULL,

    CONSTRAINT PK_Organizations PRIMARY KEY (Id)
);